# Generated by Django 3.2.8 on 2022-10-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(default='Favorite', max_length=100),
            preserve_default=False,
        ),
    ]
